"""initial paperforge schema

设计 §4.3 的 19 张表：scholarly_work 系 5 张 + 项目/论文结构域 14 张。

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-25 02:29:35.891893
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("paper_type", sa.String(length=16), nullable=False),
        sa.Column("writing_mode", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("venue_template", sa.String(length=64), nullable=True),
        sa.Column("citation_style", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paper_project_owner_id"), "paper_project", ["owner_id"], unique=False)
    op.create_table(
        "scholarly_http_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("provider_name", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scholarly_http_cache_provider_name"),
        "scholarly_http_cache",
        ["provider_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scholarly_http_cache_url_hash"), "scholarly_http_cache", ["url_hash"], unique=True
    )
    op.create_table(
        "scholarly_work",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_title", sa.Text(), nullable=False),
        sa.Column("normalized_title_hash", sa.String(length=80), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("publication_date", sa.String(length=32), nullable=True),
        sa.Column("work_type", sa.String(length=64), nullable=True),
        sa.Column("venue_name", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("pmid", sa.String(length=32), nullable=True),
        sa.Column("pmcid", sa.String(length=32), nullable=True),
        sa.Column("arxiv_id", sa.String(length=64), nullable=True),
        sa.Column("openalex_id", sa.String(length=32), nullable=True),
        sa.Column("semantic_scholar_id", sa.String(length=80), nullable=True),
        sa.Column("corpus_id", sa.String(length=32), nullable=True),
        sa.Column("is_retracted", sa.Boolean(), nullable=False),
        sa.Column("oa_status", sa.String(length=32), nullable=True),
        sa.Column("license", sa.String(length=64), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("influential_citation_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scholarly_work_arxiv_id"), "scholarly_work", ["arxiv_id"], unique=False
    )
    op.create_index(op.f("ix_scholarly_work_doi"), "scholarly_work", ["doi"], unique=False)
    op.create_index(
        op.f("ix_scholarly_work_normalized_title_hash"),
        "scholarly_work",
        ["normalized_title_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scholarly_work_openalex_id"), "scholarly_work", ["openalex_id"], unique=False
    )
    op.create_index(op.f("ix_scholarly_work_pmid"), "scholarly_work", ["pmid"], unique=False)
    op.create_index(
        op.f("ix_scholarly_work_publication_year"),
        "scholarly_work",
        ["publication_year"],
        unique=False,
    )
    op.create_table(
        "document_file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("fetched_from_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_file_work_id"), "document_file", ["work_id"], unique=False)
    op.create_table(
        "export_artifact",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("compile_log_key", sa.String(length=512), nullable=True),
        sa.Column("content_hash", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_artifact_project_id"), "export_artifact", ["project_id"], unique=False
    )
    op.create_table(
        "generation_job",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("checkpoint_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_job_project_id"), "generation_job", ["project_id"], unique=False
    )
    op.create_table(
        "library_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("rank_reason_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_pinned", sa.Boolean(), nullable=False),
        sa.Column("added_via", sa.String(length=32), nullable=False),
        sa.Column("bibtex_key", sa.String(length=128), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "bibtex_key"),
    )
    op.create_index(
        op.f("ix_library_entry_project_id"), "library_entry", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_library_entry_work_id"), "library_entry", ["work_id"], unique=False)
    op.create_table(
        "literature_card",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("contributions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("methods_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("results_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("limitations_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quotable_points_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fulltext_used", sa.Boolean(), nullable=False),
        sa.Column("extraction_model", sa.String(length=128), nullable=True),
        sa.Column("source_hash", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_literature_card_project_id"), "literature_card", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_literature_card_source_hash"), "literature_card", ["source_hash"], unique=False
    )
    op.create_index(
        op.f("ix_literature_card_work_id"), "literature_card", ["work_id"], unique=False
    )
    op.create_table(
        "outline",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tree_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outline_project_id"), "outline", ["project_id"], unique=False)
    op.create_table(
        "search_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("filters_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=True),
        sa.Column("retrieved_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_run_project_id"), "search_run", ["project_id"], unique=False)
    op.create_table(
        "user_asset",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("parsed_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_asset_project_id"), "user_asset", ["project_id"], unique=False)
    op.create_table(
        "work_author",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("author_order", sa.Integer(), nullable=False),
        sa.Column("raw_affiliation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_author_work_id"), "work_author", ["work_id"], unique=False)
    op.create_table(
        "work_identifier",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("id_type", sa.String(length=32), nullable=False),
        sa.Column("id_value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_id", "id_type", "id_value"),
    )
    op.create_index(
        op.f("ix_work_identifier_work_id"), "work_identifier", ["work_id"], unique=False
    )
    op.create_table(
        "work_url",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_type", sa.String(length=32), nullable=True),
        sa.Column("is_oa", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_url_work_id"), "work_url", ["work_id"], unique=False)
    op.create_table(
        "job_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["generation_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "seq", name="uq_job_event_job_id_seq"),
    )
    op.create_index(op.f("ix_job_event_job_id"), "job_event", ["job_id"], unique=False)
    op.create_index("ix_job_event_job_id_seq", "job_event", ["job_id", "seq"], unique=False)
    op.create_table(
        "llm_call_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_estimate", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["generation_job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["paper_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_call_log_project_id"), "llm_call_log", ["project_id"], unique=False
    )
    op.create_table(
        "paper_document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("outline_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["outline_id"],
            ["outline.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_document_project_id"), "paper_document", ["project_id"], unique=False
    )
    op.create_table(
        "paper_section",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("section_key", sa.String(length=64), nullable=False),
        sa.Column("parent_key", sa.String(length=64), nullable=True),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_ir_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cite_keys_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("asset_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["paper_document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_section_document_id"), "paper_section", ["document_id"], unique=False
    )
    op.create_table(
        "citation_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("cite_key", sa.String(length=128), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["paper_project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["paper_section.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["scholarly_work.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_citation_usage_project_id"), "citation_usage", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_citation_usage_project_id"), table_name="citation_usage")
    op.drop_table("citation_usage")
    op.drop_index(op.f("ix_paper_section_document_id"), table_name="paper_section")
    op.drop_table("paper_section")
    op.drop_index(op.f("ix_paper_document_project_id"), table_name="paper_document")
    op.drop_table("paper_document")
    op.drop_index(op.f("ix_llm_call_log_project_id"), table_name="llm_call_log")
    op.drop_table("llm_call_log")
    op.drop_index("ix_job_event_job_id_seq", table_name="job_event")
    op.drop_index(op.f("ix_job_event_job_id"), table_name="job_event")
    op.drop_table("job_event")
    op.drop_index(op.f("ix_work_url_work_id"), table_name="work_url")
    op.drop_table("work_url")
    op.drop_index(op.f("ix_work_identifier_work_id"), table_name="work_identifier")
    op.drop_table("work_identifier")
    op.drop_index(op.f("ix_work_author_work_id"), table_name="work_author")
    op.drop_table("work_author")
    op.drop_index(op.f("ix_user_asset_project_id"), table_name="user_asset")
    op.drop_table("user_asset")
    op.drop_index(op.f("ix_search_run_project_id"), table_name="search_run")
    op.drop_table("search_run")
    op.drop_index(op.f("ix_outline_project_id"), table_name="outline")
    op.drop_table("outline")
    op.drop_index(op.f("ix_literature_card_work_id"), table_name="literature_card")
    op.drop_index(op.f("ix_literature_card_source_hash"), table_name="literature_card")
    op.drop_index(op.f("ix_literature_card_project_id"), table_name="literature_card")
    op.drop_table("literature_card")
    op.drop_index(op.f("ix_library_entry_work_id"), table_name="library_entry")
    op.drop_index(op.f("ix_library_entry_project_id"), table_name="library_entry")
    op.drop_table("library_entry")
    op.drop_index(op.f("ix_generation_job_project_id"), table_name="generation_job")
    op.drop_table("generation_job")
    op.drop_index(op.f("ix_export_artifact_project_id"), table_name="export_artifact")
    op.drop_table("export_artifact")
    op.drop_index(op.f("ix_document_file_work_id"), table_name="document_file")
    op.drop_table("document_file")
    op.drop_index(op.f("ix_scholarly_work_publication_year"), table_name="scholarly_work")
    op.drop_index(op.f("ix_scholarly_work_pmid"), table_name="scholarly_work")
    op.drop_index(op.f("ix_scholarly_work_openalex_id"), table_name="scholarly_work")
    op.drop_index(op.f("ix_scholarly_work_normalized_title_hash"), table_name="scholarly_work")
    op.drop_index(op.f("ix_scholarly_work_doi"), table_name="scholarly_work")
    op.drop_index(op.f("ix_scholarly_work_arxiv_id"), table_name="scholarly_work")
    op.drop_table("scholarly_work")
    op.drop_index(op.f("ix_scholarly_http_cache_url_hash"), table_name="scholarly_http_cache")
    op.drop_index(op.f("ix_scholarly_http_cache_provider_name"), table_name="scholarly_http_cache")
    op.drop_table("scholarly_http_cache")
    op.drop_index(op.f("ix_paper_project_owner_id"), table_name="paper_project")
    op.drop_table("paper_project")
    # ### end Alembic commands ###
