"""add llm_call_log.error_code

失败调用也要留痕：否则成本面板里「失败」与「零 token 成功」无法区分。

Revision ID: 0bfdbf0c7879
Revises: 0001_initial
Create Date: 2026-07-25 10:29:02.642749
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002_llm_error_code'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call_log', sa.Column('error_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call_log', 'error_code')
    # ### end Alembic commands ###
