"""PaperForge ORM 模型（方案 §4.3）：文献域 + 项目/论文结构域。

29 张综述表 → 保留 scholarly_work 系 5 张 + 新增 14 张，共 19 张；删除的 24 张
（筛选裁决/守恒账本/质量评估/效应量）不迁移（方案 §3.3）。
"""

from db.models.auth import AppUser, AuthActionToken, UserSession
from db.models.library import (
    DOCUMENT_ACCESS_SCOPES,
    LITERATURE_ROLES,
    PDF_UPLOAD_STATUSES,
    DocumentChunk,
    DocumentFile,
    DocumentParse,
    EligibilityDecision,
    EvidenceMeasurement,
    EvidenceUnit,
    ExperimentResult,
    FulltextAttempt,
    LibraryEntry,
    LiteratureCard,
    LiteraturePdfUpload,
    ScholarlyHttpCache,
    ScholarlyWork,
    StructuredExtraction,
    WorkAuthor,
    WorkIdentifier,
    WorkUrl,
    WorkVersionRelation,
)
from db.models.paper import (
    CitationUsage,
    ClaimEntailmentCache,
    ClaimEvidenceAnchor,
    ExportArtifact,
    GenerationJob,
    JobEvent,
    LlmCallLog,
    Outline,
    PaperDocument,
    PaperProject,
    PaperSection,
    ProjectTaskProfile,
    QualityReportRecord,
    QuestionEvidenceLink,
    QuestionSynthesis,
    ResearchQuestion,
    ResearchQuestionRevision,
    SearchRun,
    TaskDefinition,
    UserAsset,
    VisualAsset,
    VisualGenerationAttempt,
    VisualSourceAsset,
)

__all__ = [
    "DOCUMENT_ACCESS_SCOPES",
    "LITERATURE_ROLES",
    "PDF_UPLOAD_STATUSES",
    "AppUser",
    "AuthActionToken",
    "CitationUsage",
    "ClaimEntailmentCache",
    "ClaimEvidenceAnchor",
    "DocumentChunk",
    "DocumentFile",
    "DocumentParse",
    "EligibilityDecision",
    "EvidenceMeasurement",
    "EvidenceUnit",
    "ExperimentResult",
    "ExportArtifact",
    "FulltextAttempt",
    "GenerationJob",
    "JobEvent",
    "LibraryEntry",
    "LiteratureCard",
    "LiteraturePdfUpload",
    "LlmCallLog",
    "Outline",
    "PaperDocument",
    "PaperProject",
    "PaperSection",
    "ProjectTaskProfile",
    "QualityReportRecord",
    "QuestionEvidenceLink",
    "QuestionSynthesis",
    "ResearchQuestion",
    "ResearchQuestionRevision",
    "TaskDefinition",
    "ScholarlyHttpCache",
    "ScholarlyWork",
    "StructuredExtraction",
    "SearchRun",
    "UserAsset",
    "UserSession",
    "VisualAsset",
    "VisualGenerationAttempt",
    "VisualSourceAsset",
    "WorkAuthor",
    "WorkIdentifier",
    "WorkUrl",
    "WorkVersionRelation",
]
