import type { LibraryEntry, Project, SearchRun } from './types';

// 后端多数接口尚为 501 占位；这些示例数据仅用于前端在降级模式下展示界面骨架。
// 一旦对应 REST 端点落地，API 客户端会自动改用真实数据。

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'demo-review-01',
    title: '扩散模型在医学影像分割中的研究综述',
    paper_type: 'review',
    writing_mode: 'assisted',
    language: 'zh',
    status: 'writing',
    venue_template: 'article',
    citation_style: 'gbt7714',
    topic: '扩散模型 · 医学影像 · 语义分割',
    library_count: 42,
    section_count: 7,
    created_at: '2026-07-18T09:12:00Z',
    updated_at: '2026-07-24T15:40:00Z',
  },
  {
    id: 'demo-original-02',
    title: 'A Lightweight Retrieval-Augmented Transformer for Edge Inference',
    paper_type: 'original',
    writing_mode: 'assisted',
    language: 'en',
    status: 'curating',
    venue_template: 'IEEEtran',
    citation_style: 'ieee',
    topic: 'edge inference · retrieval augmentation',
    contribution_points: [
      '提出面向边缘设备的轻量检索增强结构',
      '在三个基准上取得 SOTA 延迟/精度折衷',
    ],
    library_count: 18,
    section_count: 8,
    created_at: '2026-07-21T02:30:00Z',
    updated_at: '2026-07-24T11:05:00Z',
  },
  {
    id: 'demo-review-03',
    title: '联邦学习中的隐私保护机制综述',
    paper_type: 'review',
    writing_mode: 'auto',
    language: 'zh',
    status: 'searching',
    venue_template: 'llncs',
    citation_style: 'author_year',
    topic: '联邦学习 · 差分隐私 · 安全聚合',
    library_count: 6,
    section_count: 0,
    created_at: '2026-07-24T08:00:00Z',
    updated_at: '2026-07-24T08:45:00Z',
  },
];

export const MOCK_LIBRARY: LibraryEntry[] = [
  {
    id: 'le-1',
    status: 'selected',
    relevance_score: 0.94,
    rank_reason: '标题与查询高度匹配（扩散 + 分割），近三年高被引',
    user_pinned: true,
    literature_role: 'core',
    added_via: 'search',
    bibtex_key: 'kazerouni2023diffusion',
    verified_at: '2026-07-19T10:00:00Z',
    utilization: {
      fulltext_status: 'available',
      fulltext_source: 'oa',
      evidence_status: 'extracted',
      assignment_status: 'assigned',
      citation_status: 'cited',
      evidence_count: 8,
      assignment_count: 3,
      citation_count: 2,
      usage_evaluated: true,
      unused_reason: null,
    },
    work: {
      id: 'w-1',
      canonical_title: 'Diffusion Models in Medical Imaging: A Comprehensive Survey',
      authors: ['A. Kazerouni', 'E. K. Aghdam', 'R. Azad'],
      publication_year: 2023,
      venue_name: 'Medical Image Analysis',
      doi: '10.1016/j.media.2023.102846',
      oa_status: 'hybrid',
      is_retracted: false,
      citation_count: 612,
      abstract:
        '本文系统综述了扩散模型在医学影像重建、分割、去噪等任务中的应用，梳理了条件生成与采样加速的主流方案。',
    },
    card: {
      summary: '面向医学影像的扩散模型全景综述，覆盖重建/分割/配准四大任务族。',
      contributions: ['首个医学影像扩散模型系统分类', '开源基线复现清单'],
      methods: ['DDPM', 'score-based SDE', 'latent diffusion'],
      results: ['在多项分割基准上优于 GAN 基线'],
      limitations: ['采样开销大', '缺乏统一评测协议'],
      quotable_points: ['扩散模型在小样本医学分割中展现更稳的边界一致性。'],
      fulltext_used: true,
      extraction_model: 'extractor-mini',
    },
  },
  {
    id: 'le-2',
    status: 'candidate',
    relevance_score: 0.88,
    rank_reason: '方法相关（score-based），被雪球引用命中',
    added_via: 'snowball',
    bibtex_key: null,
    verified_at: null,
    work: {
      id: 'w-2',
      canonical_title: 'Score-Based Generative Modeling through Stochastic Differential Equations',
      authors: ['Y. Song', 'J. Sohl-Dickstein', 'D. P. Kingma'],
      publication_year: 2021,
      venue_name: 'ICLR',
      doi: '10.48550/arXiv.2011.13456',
      arxiv_id: '2011.13456',
      oa_status: 'green',
      is_retracted: false,
      citation_count: 5400,
    },
  },
  {
    id: 'le-3',
    status: 'candidate',
    relevance_score: 0.72,
    rank_reason: '主题相关但偏自然图像，需人工判断',
    added_via: 'search',
    bibtex_key: null,
    verified_at: null,
    work: {
      id: 'w-3',
      canonical_title: 'Denoising Diffusion Probabilistic Models',
      authors: ['J. Ho', 'A. Jain', 'P. Abbeel'],
      publication_year: 2020,
      venue_name: 'NeurIPS',
      doi: '10.48550/arXiv.2006.11239',
      arxiv_id: '2006.11239',
      oa_status: 'green',
      is_retracted: false,
      citation_count: 12800,
    },
  },
  {
    id: 'le-4',
    status: 'excluded',
    relevance_score: 0.41,
    rank_reason: '仅在引言提及分割，非核心相关',
    added_via: 'search',
    bibtex_key: null,
    verified_at: null,
    work: {
      id: 'w-4',
      canonical_title: 'A Review of Deep Learning for Natural Image Generation',
      authors: ['L. Chen', 'M. Zhou'],
      publication_year: 2022,
      venue_name: 'arXiv',
      arxiv_id: '2201.00001',
      oa_status: 'green',
      is_retracted: false,
      citation_count: 88,
    },
  },
];

export const MOCK_SEARCH_RUNS: SearchRun[] = [
  {
    id: 'sr-1',
    provider: 'openalex',
    query_text: 'diffusion model medical image segmentation',
    hit_count: 1284,
    retrieved_count: 200,
    status: 'succeeded',
    executed_at: '2026-07-24T15:10:00Z',
  },
  {
    id: 'sr-2',
    provider: 'arxiv',
    query_text: 'diffusion segmentation',
    hit_count: 412,
    retrieved_count: 120,
    status: 'succeeded',
    executed_at: '2026-07-24T15:10:00Z',
  },
  {
    id: 'sr-3',
    provider: 'europe_pmc',
    query_text: 'diffusion model medical segmentation survey',
    hit_count: 903,
    retrieved_count: 150,
    status: 'succeeded',
    executed_at: '2026-07-24T15:11:00Z',
  },
  {
    id: 'sr-4',
    provider: 'crossref',
    query_text: 'diffusion medical imaging',
    hit_count: 0,
    retrieved_count: 0,
    status: 'failed',
    executed_at: '2026-07-24T15:11:00Z',
    error: 'rate limited (429)',
  },
];
