upstream capacity_api {
    server 127.0.0.1:28081;
    server 127.0.0.1:28082;
    keepalive 32;
}
server {
    listen 127.0.0.1:28080;
    client_max_body_size 68m;
    location / {
        proxy_pass http://capacity_api;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_read_timeout 3h;
    }
}
