"""Domain repositories that centralize cross-pipeline database invariants."""

from db.repositories.assets import (
    asset_render_index,
    create_asset,
    delete_asset,
    get_asset,
    list_assets,
    parsed_asset_payloads,
)
from db.repositories.documents import (
    create_document,
    create_outline,
    get_outline,
    get_section,
    latest_document,
    latest_outline,
    list_citation_usage,
    list_sections,
    replace_citation_usage,
    update_outline_tree,
    upsert_section,
)
from db.repositories.exports import list_export_artifacts
from db.repositories.jobs import (
    append_job_event,
    create_job,
    get_job,
    list_job_events,
    list_jobs,
    lock_generation_job_stmt,
    next_job_event_seq_stmt,
    project_llm_cost,
    record_llm_call,
    update_job,
)
from db.repositories.library import (
    assign_bibtex_key,
    delete_entry,
    find_cached_card,
    get_cards,
    get_entry,
    get_writing_whitelist,
    list_entries,
    reference_metadata_payload,
    set_entry_status,
    upsert_card,
    upsert_entry,
    writing_whitelist_stmt,
)
from db.repositories.projects import (
    create_project,
    get_project,
    list_projects,
    project_counters,
    set_project_status,
    update_project_scope,
)
from db.repositories.search_runs import list_search_runs, record_search_run
from db.repositories.works import get_work_authors, get_work_urls, upsert_work

__all__ = [
    "parsed_asset_payloads",
    "list_assets",
    "get_asset",
    "delete_asset",
    "create_asset",
    "asset_render_index",
    "list_export_artifacts",
    "upsert_section",
    "update_outline_tree",
    "replace_citation_usage",
    "list_sections",
    "list_citation_usage",
    "latest_outline",
    "latest_document",
    "get_section",
    "get_outline",
    "create_outline",
    "create_document",
    "append_job_event",
    "assign_bibtex_key",
    "create_job",
    "create_project",
    "delete_entry",
    "find_cached_card",
    "get_cards",
    "get_entry",
    "get_job",
    "get_project",
    "get_work_authors",
    "get_work_urls",
    "get_writing_whitelist",
    "list_entries",
    "list_job_events",
    "list_jobs",
    "list_projects",
    "list_search_runs",
    "lock_generation_job_stmt",
    "next_job_event_seq_stmt",
    "project_counters",
    "project_llm_cost",
    "record_llm_call",
    "record_search_run",
    "reference_metadata_payload",
    "set_entry_status",
    "set_project_status",
    "update_job",
    "update_project_scope",
    "upsert_card",
    "upsert_entry",
    "upsert_work",
    "writing_whitelist_stmt",
]
